name: Deploy docs

on:
  push:
    branches:
    - master

env:
  VCPKG_COMMIT: 4990d2b9510876531eb7e73eeba09210178e804f

jobs:
  docs:
    runs-on: ubuntu-latest

    if: github.repository_owner == 'friendlyanon'

    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-python@v2
      with: { python-version: "3.8" }

    - name: Install m.css dependencies
      run: pip3 install jinja2 Pygments

    - name: Install Doxygen
      run: sudo apt-get update -q
        && sudo apt-get install doxygen -q -y

    - name: Build docs
      run: cmake -P cmake/docs.cmake

    - name: Deploy docs
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ github.token }}
        publish_dir: build/docs/html
